site_name: Modul 169 - Services mit Containern bereitstellen
site_url: "https://gbssg.github.io/modul169"
repo_url: "https://github.com/gbssg/m169"
edit_uri: "blob/master/docs/"

nav:
  - 0. Übersicht: index.md
  - 1. Einführung:
    - Überblick: 1-10.md
  - 2. Umgebung / Architektur:
    - Grundprinzipien: 2-10.md
  - 3. Datenverbindungen:
    - Übersicht: 3-10.md
  - 4. Sicherheit:
    - Betrieb: 4-10.md
  - 5. Dokumentation:
    - Übersicht: 1-10.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate
    - navigation.instant

plugins:
  - mermaid2
  - markmap
  - search
  - git-revision-date

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2021 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Informatik <span class='green'>|</span> Modul 169
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: gbssg.ch

