site_name: Modul 114 - Codierungs-, Kompressions- und Verschlüsselungsverfahren einsetzen
site_url: "https://gbssg.github.io/modul114"

nav:
  - 0. Übersicht: index.md
  - 1. Codierung:
    - Begriff Codierung: 1-10.md
    - Arten von Codes: 1-20.md
    - Fehlererkennung und -behebung: 1-30.md
    - Binärcode: 1-40.md
    - Zahlensysteme: 1-50.md
    - Logische Operatoren: 1-60.md
    - Bildcodierung: 1-70.md
  - 2. Komprimierung:
    - Funktionsweise Komprimierung: 2-10.md
    - Normen und Standards: 2-20.md
  - 3. Verschlüsselung:
    - Begrifflichkeiten: 3-10.md
    - Symmetrische Verschlüsselungsmethoden: 3-20.md
    - Asymmetrische Verschlüsselungsmethoden: 3-30.md
    - Zertifikate: 3-40.md
    - Signaturen: 3-50.md
  - 10. Beginn:
    - Übersicht Elemente: 10-10.md

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon-32x32.png  
  language: de
  features:
    - navigation.instant
    - toc.integrate
    - navigation.instant

plugins:
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - footnotes
  - meta
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
      toc_depth: 2

  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2021 <a href='https://www.gbssg.ch'><span style='font-weight:1000'>gbs</span>sg.ch</a> <span class='green'>|</span> Informatik <span class='green'>|</span> Modul 114
extra:
  social:
    - icon: material/home
      link: https://www.gbssg.ch
      name: gbssg.ch
